FROM maven:3.9.5-amazoncorretto-17 as build
WORKDIR /usr/app
COPY . /usr/app/
RUN mvn spring-javaformat:apply clean package -Dskiptests

FROM openjdk:11-jdk
COPY --from=build /usr/app/target/spring-petclinic-2.7.0.jar /
EXPOSE 8080
CMD ["java","-jar","spring-petclinic-2.7.0.jar"]
